## Tensorflow ##

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense

In [2]:
text = "Exploding and vanishing gradients is the  the major drawback of RNN"
chars = sorted(list(set(text)))
char_to_index = {char: i for i, char in enumerate(chars)}
char_to_index

{' ': 0,
 'E': 1,
 'N': 2,
 'R': 3,
 'a': 4,
 'b': 5,
 'c': 6,
 'd': 7,
 'e': 8,
 'f': 9,
 'g': 10,
 'h': 11,
 'i': 12,
 'j': 13,
 'k': 14,
 'l': 15,
 'm': 16,
 'n': 17,
 'o': 18,
 'p': 19,
 'r': 20,
 's': 21,
 't': 22,
 'v': 23,
 'w': 24,
 'x': 25}

In [3]:
index_to_char = {i: char for i, char in enumerate(chars)}
index_to_char

{0: ' ',
 1: 'E',
 2: 'N',
 3: 'R',
 4: 'a',
 5: 'b',
 6: 'c',
 7: 'd',
 8: 'e',
 9: 'f',
 10: 'g',
 11: 'h',
 12: 'i',
 13: 'j',
 14: 'k',
 15: 'l',
 16: 'm',
 17: 'n',
 18: 'o',
 19: 'p',
 20: 'r',
 21: 's',
 22: 't',
 23: 'v',
 24: 'w',
 25: 'x'}

In [11]:
seq_length = 3
sequences = []
labels = []
 
for i in range(len(text) - seq_length):
    seq = text[i:i+seq_length]
    label = text[i+seq_length]
    sequences.append([char_to_index[char] for char in seq])
    labels.append(char_to_index[label])
# print(labels, sequences)

In [13]:
X = np.array(sequences)
X

array([[ 1, 25, 19],
       [25, 19, 15],
       [19, 15, 18],
       [15, 18,  7],
       [18,  7, 12],
       [ 7, 12, 17],
       [12, 17, 10],
       [17, 10,  0],
       [10,  0,  4],
       [ 0,  4, 17],
       [ 4, 17,  7],
       [17,  7,  0],
       [ 7,  0, 23],
       [ 0, 23,  4],
       [23,  4, 17],
       [ 4, 17, 12],
       [17, 12, 21],
       [12, 21, 11],
       [21, 11, 12],
       [11, 12, 17],
       [12, 17, 10],
       [17, 10,  0],
       [10,  0, 10],
       [ 0, 10, 20],
       [10, 20,  4],
       [20,  4,  7],
       [ 4,  7, 12],
       [ 7, 12,  8],
       [12,  8, 17],
       [ 8, 17, 22],
       [17, 22, 21],
       [22, 21,  0],
       [21,  0, 12],
       [ 0, 12, 21],
       [12, 21,  0],
       [21,  0, 22],
       [ 0, 22, 11],
       [22, 11,  8],
       [11,  8,  0],
       [ 8,  0,  0],
       [ 0,  0, 22],
       [ 0, 22, 11],
       [22, 11,  8],
       [11,  8,  0],
       [ 8,  0, 16],
       [ 0, 16,  4],
       [16,  4, 13],
       [ 4, 1

In [14]:
y = np.array(labels)
y

array([15, 18,  7, 12, 17, 10,  0,  4, 17,  7,  0, 23,  4, 17, 12, 21, 11,
       12, 17, 10,  0, 10, 20,  4,  7, 12,  8, 17, 22, 21,  0, 12, 21,  0,
       22, 11,  8,  0,  0, 22, 11,  8,  0, 16,  4, 13, 18, 20,  0,  7, 20,
        4, 24,  5,  4,  6, 14,  0, 18,  9,  0,  3,  2,  2])

In [15]:
X_one_hot = tf.one_hot(X, len(chars))
y_one_hot = tf.one_hot(y, len(chars))

2024-04-01 02:11:12.047194: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-04-01 02:11:12.151634: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


**Model Building**

In [16]:
model = Sequential()
model.add(SimpleRNN(50, input_shape=(seq_length, len(chars)), activation='relu'))
model.add(Dense(len(chars), activation='softmax'))

In [17]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [18]:
model.fit(X_one_hot, y_one_hot, epochs=100)

Epoch 1/100
2/2 [==============================] - 0s 6ms/step - loss: 3.2762 - accuracy: 0.0312
Epoch 2/100
2/2 [==============================] - 0s 3ms/step - loss: 3.2556 - accuracy: 0.0312
Epoch 3/100
2/2 [==============================] - 0s 3ms/step - loss: 3.2373 - accuracy: 0.0312
Epoch 4/100
2/2 [==============================] - 0s 3ms/step - loss: 3.2197 - accuracy: 0.0469
Epoch 5/100
2/2 [==============================] - 0s 3ms/step - loss: 3.2028 - accuracy: 0.0469
Epoch 6/100
2/2 [==============================] - 0s 3ms/step - loss: 3.1860 - accuracy: 0.0781
Epoch 7/100
2/2 [==============================] - 0s 3ms/step - loss: 3.1691 - accuracy: 0.0938
Epoch 8/100
2/2 [==============================] - 0s 3ms/step - loss: 3.1520 - accuracy: 0.1094
Epoch 9/100
2/2 [==============================] - 0s 3ms/step - loss: 3.1345 - accuracy: 0.1406
Epoch 10/100
2/2 [==============================] - 0s 3ms/step - loss: 3.1178 - accuracy: 0.1719
Epoch 11/100
2/2 [===========

2/2 [==============================] - 0s 2ms/step - loss: 0.7298 - accuracy: 0.8906
Epoch 85/100
2/2 [==============================] - 0s 3ms/step - loss: 0.7061 - accuracy: 0.8906
Epoch 86/100
2/2 [==============================] - 0s 2ms/step - loss: 0.6822 - accuracy: 0.9062
Epoch 87/100
2/2 [==============================] - 0s 2ms/step - loss: 0.6589 - accuracy: 0.9062
Epoch 88/100
2/2 [==============================] - 0s 2ms/step - loss: 0.6358 - accuracy: 0.9062
Epoch 89/100
2/2 [==============================] - 0s 2ms/step - loss: 0.6142 - accuracy: 0.9062
Epoch 90/100
2/2 [==============================] - 0s 2ms/step - loss: 0.5928 - accuracy: 0.9219
Epoch 91/100
2/2 [==============================] - 0s 2ms/step - loss: 0.5730 - accuracy: 0.9375
Epoch 92/100
2/2 [==============================] - 0s 2ms/step - loss: 0.5528 - accuracy: 0.9375
Epoch 93/100
2/2 [==============================] - 0s 2ms/step - loss: 0.5335 - accuracy: 0.9375
Epoch 94/100
2/2 [===============

In [19]:
start_seq = "Exploding and vanishing "
generated_text = start_seq
 
for i in range(50):
    x = np.array([[char_to_index[char] for char in generated_text[-seq_length:]]])
    x_one_hot = tf.one_hot(x, len(chars))
    prediction = model.predict(x_one_hot)
    next_index = np.argmax(prediction)
    next_char = index_to_char[next_index]
    generated_text += next_char

print("Generated Text:")
print(generated_text)

1/1 [==============================] - 0s 12ms/step
Generated Text:
Exploding and vanishing and vanishing and vanishing and vanishing and vani


In [21]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.nn.functional import one_hot, softmax

In [22]:
X = torch.tensor(sequences)
X

tensor([[ 1, 25, 19],
        [25, 19, 15],
        [19, 15, 18],
        [15, 18,  7],
        [18,  7, 12],
        [ 7, 12, 17],
        [12, 17, 10],
        [17, 10,  0],
        [10,  0,  4],
        [ 0,  4, 17],
        [ 4, 17,  7],
        [17,  7,  0],
        [ 7,  0, 23],
        [ 0, 23,  4],
        [23,  4, 17],
        [ 4, 17, 12],
        [17, 12, 21],
        [12, 21, 11],
        [21, 11, 12],
        [11, 12, 17],
        [12, 17, 10],
        [17, 10,  0],
        [10,  0, 10],
        [ 0, 10, 20],
        [10, 20,  4],
        [20,  4,  7],
        [ 4,  7, 12],
        [ 7, 12,  8],
        [12,  8, 17],
        [ 8, 17, 22],
        [17, 22, 21],
        [22, 21,  0],
        [21,  0, 12],
        [ 0, 12, 21],
        [12, 21,  0],
        [21,  0, 22],
        [ 0, 22, 11],
        [22, 11,  8],
        [11,  8,  0],
        [ 8,  0,  0],
        [ 0,  0, 22],
        [ 0, 22, 11],
        [22, 11,  8],
        [11,  8,  0],
        [ 8,  0, 16],
        [ 

In [23]:
y = torch.tensor(labels)
y

tensor([15, 18,  7, 12, 17, 10,  0,  4, 17,  7,  0, 23,  4, 17, 12, 21, 11, 12,
        17, 10,  0, 10, 20,  4,  7, 12,  8, 17, 22, 21,  0, 12, 21,  0, 22, 11,
         8,  0,  0, 22, 11,  8,  0, 16,  4, 13, 18, 20,  0,  7, 20,  4, 24,  5,
         4,  6, 14,  0, 18,  9,  0,  3,  2,  2])

In [24]:
X_one_hot = one_hot(X, num_classes=len(chars)).float()
y_one_hot = one_hot(y, num_classes=len(chars)).float()

In [29]:
class SimpleRNNModel(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(SimpleRNNModel, self).__init__()
        self.rnn = nn.RNN(input_size, hidden_size, nonlinearity='relu', batch_first=True)
        self.fc = nn.Linear(hidden_size, output_size)
    def forward(self, x):
        out, _ = self.rnn(x)
        out = self.fc(out[:, -1, :])
        return out

In [30]:
# Model build
model = SimpleRNNModel(input_size=len(chars), hidden_size=50, output_size=len(chars))

In [31]:
# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters())

In [32]:
# Training loop
for epoch in range(100):
    optimizer.zero_grad()
    outputs = model(X_one_hot)
    loss = criterion(outputs, y)
    loss.backward()
    optimizer.step()

    if (epoch+1) % 10 == 0:
        print(f'Epoch [{epoch+1}/100], Loss: {loss.item()}')

Epoch [10/100], Loss: 3.1915154457092285
Epoch [20/100], Loss: 3.1152400970458984
Epoch [30/100], Loss: 2.996299982070923
Epoch [40/100], Loss: 2.8263099193573
Epoch [50/100], Loss: 2.7296624183654785
Epoch [60/100], Loss: 2.6324095726013184
Epoch [70/100], Loss: 2.520597457885742
Epoch [80/100], Loss: 2.372476816177368
Epoch [90/100], Loss: 2.181813955307007
Epoch [100/100], Loss: 1.9495078325271606


In [33]:
# Text generation
model.eval()
generated_text = "Exploding and vanishing "

with torch.no_grad():
    for _ in range(50):
        x = torch.tensor([[char_to_index[char] for char in generated_text[-seq_length:]]])
        x_one_hot = one_hot(x, num_classes=len(chars)).float()
        outputs = model(x_one_hot)
        _, predicted_index = torch.max(outputs, -1)
        next_char = index_to_char[predicted_index.item()]
        generated_text += next_char

print("Generated Text:")
print(generated_text)

Generated Text:
Exploding and vanishing ani a i                                           
